# Generated by Django 4.2.4 on 2023-08-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=155)),
                ('resource_link', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Resources',
            },
        ),
    ]
