# Generated by Django 4.2.4 on 2023-08-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coursecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesOfCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course_creator', models.CharField(max_length=255)),
                ('course_link', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'CoursesOfCategories',
            },
        ),
    ]
