# Generated by Django 4.2.4 on 2023-08-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_coursesofcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesofcategory',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.coursecategory'),
            preserve_default=False,
        ),
    ]
