# Generated by Django 4.2.4 on 2023-08-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_coursesofcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesofcategory',
            name='title',
            field=models.TextField(),
        ),
    ]
