# Generated by Django 4.2.4 on 2023-08-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_coursesofcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesofcategory',
            name='course_creator',
            field=models.TextField(max_length=255),
        ),
    ]
