# Generated by Django 4.2.4 on 2023-08-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_coursesofcategory_course_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_name',
            field=models.TextField(),
        ),
    ]
